name: itslive_vortex
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - ipyleaflet
  - geopandas
  - matplotlib-base
  - pyproj
  - ipympl
  - xarray
  - h5netcdf
  - netcdf4
  - cartopy
  - pip
  - pip:
    - git+https://github.com/nasa-jpl/itslive-vortex.git
    - utm
